package codegen

// fieldsTemplate é o template para gerar arquivos de campos tipados.
const fieldsTemplate = `// Code generated by genus generate. DO NOT EDIT.

package {{.Package}}

import (
	"github.com/go-genus/genus/query"
	{{- if .ImportCore}}
	"github.com/go-genus/genus/core"
	{{- end}}
)

// {{.Name}}Fields contém todos os campos tipados para a struct {{.Name}}.
// Use estes campos para construir queries type-safe.
//
// Exemplo:
//   genus.Table[{{.Name}}]().
//       Where({{.Name}}Fields.{{(index .Fields 0).Name}}.Eq("value")).
//       Find(ctx)
var {{.Name}}Fields = struct {
	{{- range .Fields}}
	{{.Name}} {{.FieldType}}
	{{- end}}
}{
	{{- range .Fields}}
	{{.Name}}: {{.FieldType | fieldConstructor}}("{{.ColumnName}}"),
	{{- end}}
}
`

// fieldConstructor retorna o construtor apropriado para um tipo de campo.
func fieldConstructor(fieldType string) string {
	switch fieldType {
	case "query.StringField":
		return "query.NewStringField"
	case "query.IntField":
		return "query.NewIntField"
	case "query.Int64Field":
		return "query.NewInt64Field"
	case "query.BoolField":
		return "query.NewBoolField"
	case "query.Float64Field":
		return "query.NewFloat64Field"
	case "query.OptionalStringField":
		return "query.NewOptionalStringField"
	case "query.OptionalIntField":
		return "query.NewOptionalIntField"
	case "query.OptionalInt64Field":
		return "query.NewOptionalInt64Field"
	case "query.OptionalBoolField":
		return "query.NewOptionalBoolField"
	case "query.OptionalFloat64Field":
		return "query.NewOptionalFloat64Field"
	default:
		return "query.NewStringField"
	}
}

// Registra a função helper no template
func init() {
	// Esta função será usada no template acima via pipe: {{.FieldType | fieldConstructor}}
}
