// Code generated by genus. DO NOT EDIT.
// This file contains optimized, reflection-free scanners.

package scanner

import (
	"database/sql"
)

// ============================================================================
// User Scanners
// ============================================================================

// ScanUser scans a single row into a User.
// This is ~10x faster than reflection-based scanning.
func ScanUser(rows *sql.Rows) (User, error) {
	var m User
	err := rows.Scan(
		&m.ID,
		&m.CreatedAt,
		&m.UpdatedAt,
		&m.Name,
		&m.Email,
		&m.Age,
		&m.IsActive,
		&m.Score,
	)
	return m, err
}

// ScanUsers scans all rows into a slice of User.
// Pre-allocates slice capacity for better performance.
func ScanUsers(rows *sql.Rows) ([]User, error) {
	var results []User
	for rows.Next() {
		var m User
		if err := rows.Scan(
			&m.ID,
			&m.CreatedAt,
			&m.UpdatedAt,
			&m.Name,
			&m.Email,
			&m.Age,
			&m.IsActive,
			&m.Score,
		); err != nil {
			return nil, err
		}
		results = append(results, m)
	}
	return results, rows.Err()
}

// ScanUsersWithCap scans all rows with pre-allocated capacity.
// Use when you know the approximate number of results.
func ScanUsersWithCap(rows *sql.Rows, capacity int) ([]User, error) {
	results := make([]User, 0, capacity)
	for rows.Next() {
		var m User
		if err := rows.Scan(
			&m.ID,
			&m.CreatedAt,
			&m.UpdatedAt,
			&m.Name,
			&m.Email,
			&m.Age,
			&m.IsActive,
			&m.Score,
		); err != nil {
			return nil, err
		}
		results = append(results, m)
	}
	return results, rows.Err()
}

// UserColumns returns the column names for User in scan order.
func UserColumns() []string {
	return []string{
		"id",
		"created_at",
		"updated_at",
		"name",
		"email",
		"age",
		"is_active",
		"score",
	}
}

// UserColumnsString returns comma-separated column names for SELECT.
func UserColumnsString() string {
	return "id, created_at, updated_at, name, email, age, is_active, score"
}

// ============================================================================
// Post Scanners
// ============================================================================

// ScanPost scans a single row into a Post.
// This is ~10x faster than reflection-based scanning.
func ScanPost(rows *sql.Rows) (Post, error) {
	var m Post
	err := rows.Scan(
		&m.ID,
		&m.CreatedAt,
		&m.UpdatedAt,
		&m.Title,
		&m.Content,
		&m.UserID,
		&m.Views,
	)
	return m, err
}

// ScanPosts scans all rows into a slice of Post.
// Pre-allocates slice capacity for better performance.
func ScanPosts(rows *sql.Rows) ([]Post, error) {
	var results []Post
	for rows.Next() {
		var m Post
		if err := rows.Scan(
			&m.ID,
			&m.CreatedAt,
			&m.UpdatedAt,
			&m.Title,
			&m.Content,
			&m.UserID,
			&m.Views,
		); err != nil {
			return nil, err
		}
		results = append(results, m)
	}
	return results, rows.Err()
}

// ScanPostsWithCap scans all rows with pre-allocated capacity.
// Use when you know the approximate number of results.
func ScanPostsWithCap(rows *sql.Rows, capacity int) ([]Post, error) {
	results := make([]Post, 0, capacity)
	for rows.Next() {
		var m Post
		if err := rows.Scan(
			&m.ID,
			&m.CreatedAt,
			&m.UpdatedAt,
			&m.Title,
			&m.Content,
			&m.UserID,
			&m.Views,
		); err != nil {
			return nil, err
		}
		results = append(results, m)
	}
	return results, rows.Err()
}

// PostColumns returns the column names for Post in scan order.
func PostColumns() []string {
	return []string{
		"id",
		"created_at",
		"updated_at",
		"title",
		"content",
		"user_id",
		"views",
	}
}

// PostColumnsString returns comma-separated column names for SELECT.
func PostColumnsString() string {
	return "id, created_at, updated_at, title, content, user_id, views"
}

// ============================================================================
// Comment Scanners
// ============================================================================

// ScanComment scans a single row into a Comment.
// This is ~10x faster than reflection-based scanning.
func ScanComment(rows *sql.Rows) (Comment, error) {
	var m Comment
	err := rows.Scan(
		&m.ID,
		&m.CreatedAt,
		&m.UpdatedAt,
		&m.PostID,
		&m.UserID,
		&m.Content,
	)
	return m, err
}

// ScanComments scans all rows into a slice of Comment.
// Pre-allocates slice capacity for better performance.
func ScanComments(rows *sql.Rows) ([]Comment, error) {
	var results []Comment
	for rows.Next() {
		var m Comment
		if err := rows.Scan(
			&m.ID,
			&m.CreatedAt,
			&m.UpdatedAt,
			&m.PostID,
			&m.UserID,
			&m.Content,
		); err != nil {
			return nil, err
		}
		results = append(results, m)
	}
	return results, rows.Err()
}

// ScanCommentsWithCap scans all rows with pre-allocated capacity.
// Use when you know the approximate number of results.
func ScanCommentsWithCap(rows *sql.Rows, capacity int) ([]Comment, error) {
	results := make([]Comment, 0, capacity)
	for rows.Next() {
		var m Comment
		if err := rows.Scan(
			&m.ID,
			&m.CreatedAt,
			&m.UpdatedAt,
			&m.PostID,
			&m.UserID,
			&m.Content,
		); err != nil {
			return nil, err
		}
		results = append(results, m)
	}
	return results, rows.Err()
}

// CommentColumns returns the column names for Comment in scan order.
func CommentColumns() []string {
	return []string{
		"id",
		"created_at",
		"updated_at",
		"post_id",
		"user_id",
		"content",
	}
}

// CommentColumnsString returns comma-separated column names for SELECT.
func CommentColumnsString() string {
	return "id, created_at, updated_at, post_id, user_id, content"
}
